# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
