# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20170724_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='joined',
            field=models.ManyToManyField(related_name='joining', to='travel.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travel.User'),
            preserve_default=False,
        ),
    ]
